"""initial schema

Revision ID: 7c59f11d23e3
Revises: 
Create Date: 2026-09-07 15:05:25.627323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c59f11d23e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("role IN ('EMPLOYEE', 'AGENT', 'ADMIN')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('tickets',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='MEDIUM', nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_by_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_to_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('closed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.CheckConstraint("priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')", name=op.f('ck_tickets_priority')),
    sa.CheckConstraint("status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')", name=op.f('ck_tickets_status')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tickets_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tickets_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tickets_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_tickets_ticket_number'))
    )
    op.create_index('ix_tickets_assigned_to_status_created_at', 'tickets', ['assigned_to_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_tickets_category_id', 'tickets', ['category_id'], unique=False)
    op.create_index('ix_tickets_created_by_created_at', 'tickets', ['created_by_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_status_priority_created_at', 'tickets', ['status', 'priority', 'created_at'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('author_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='PUBLIC', nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("visibility IN ('PUBLIC', 'INTERNAL')", name=op.f('ck_ticket_comments_visibility')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments'))
    )
    op.create_index('ix_ticket_comments_ticket_id_created_at', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('actor_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_ticket_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_events_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_index('ix_ticket_events_ticket_id_created_at', 'ticket_events', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_id_created_at', table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index('ix_ticket_comments_ticket_id_created_at', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index('ix_tickets_status_priority_created_at', table_name='tickets')
    op.drop_index('ix_tickets_created_by_created_at', table_name='tickets')
    op.drop_index('ix_tickets_category_id', table_name='tickets')
    op.drop_index('ix_tickets_assigned_to_status_created_at', table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
